"""WorkTimer model: the user's single ACTIVE Work Session.

This is temporary state — "this user is currently working on this issue."
It is deliberately NOT connected to login/logout, sessions or page activity:
login duration is never counted as work time.

Rules enforced at the database level:

* One active timer per user — enforced by the partial unique index
  ``uq_work_timer_one_active`` on ``user_id WHERE stopped_at IS NULL``. Two
  race-y Start requests cannot both succeed; PostgreSQL rejects the second
  insert. This does not rely on frontend button disabling.
* Every timer is project-scoped (``project_id``) so per-project reporting can
  never leak across projects.
* ``started_at`` is generated by the backend (server/database timestamp) — the
  browser clock is never treated as authoritative.
* Stopping finalizes a ``WorkLog`` (same table as manual Log Work) inside the
  same transaction and records ``work_log_id`` so a stopped timer is fully
  auditable. The timer row is kept for audit, never deleted: ``stopped_at``
  marks it closed, so a duplicate Stop can never create a second log.

Ownership semantics:

* ``user_id`` is ALWAYS the authenticated user and can never be forged from
  the frontend (no ``worked_by`` parameter exists on the timer endpoints).
* If the underlying issue is later reassigned to someone else, this timer and
  the resulting Work Log stay with the original worker.
"""
from datetime import datetime

from app.extensions import db


class WorkTimer(db.Model):
    __tablename__ = 'work_timers'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    project_id = db.Column(db.Integer, db.ForeignKey('projects.id'), nullable=False)
    issue_id = db.Column(db.Integer, db.ForeignKey('issues.id'), nullable=False)
    started_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    stopped_at = db.Column(db.DateTime, nullable=True)
    work_log_id = db.Column(db.Integer, db.ForeignKey('work_logs.id'), nullable=True)
    created_at = db.Column(db.DateTime, nullable=True, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=True, default=datetime.utcnow, onupdate=datetime.utcnow)

    user = db.relationship('User', foreign_keys=[user_id])
    project = db.relationship('Project', foreign_keys=[project_id])
    issue = db.relationship('Issue', foreign_keys=[issue_id])
    work_log = db.relationship('WorkLog', foreign_keys=[work_log_id])

    __table_args__ = (
        # Database-level "one active timer per user" guarantee. PostgreSQL
        # supports partial indexes; this is the concurrency-safe enforcement.
        db.Index('uq_work_timer_one_active', 'user_id',
                 unique=True,
                 postgresql_where=db.text('stopped_at IS NULL')),
        db.Index('ix_work_timer_user', 'user_id'),
        db.Index('ix_work_timer_issue', 'issue_id'),
    )